# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  lint:
    docker:
      - image: archlinux:latest
    steps:
      - checkout
      - run:
          command: pacman -Syy && pacman -S --noconfirm cmake git make clang gcc findutils
      - run:
          command: find ./src/ -iname "*.h" -o -iname "*.cpp" | xargs clang-format --dry-run -Werror
      - run:
          command: find ./tests/ -iname "*.h" -o -iname "*.cpp" | xargs clang-format --dry-run -Werror
  build:
    docker:
      - image: archlinux:latest
    steps:
      - checkout
      - run:
          command: pacman -Syy && pacman -S --noconfirm cmake git make clang gcc
      - run:
          command: cmake -S . -B Debug -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=TRUE
      - run:
          command: cmake --build Debug --parallel
  tests:
    docker:
      - image: archlinux:latest
    steps:
      - checkout
      - run:
          command: pacman -Syy && pacman -S --noconfirm cmake git make clang gcc
      - run:
          command: cmake -S . -B Debug -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=TRUE
      - run:
          command: cmake --build Debug --parallel
      - run:
          command: ctest --test-dir Debug/tests --verbose

workflows:
  windowmanager:
    jobs:
      - lint
      - build
      - tests:
          requires:
            - build
