# See: https://circleci.com/docs/configuration-reference
version: 2.1

executors:
  archexecutor:
    docker:
      - image: ym07/windowmanagerbase:latest
        auth:
          username: ym07
          password: $DOCKERHUB_TOKEN
    working_directory: /workspace

jobs:
  check_version_increment:
    executor: archexecutor
    steps:
      - checkout
      - run:
          command: export TAG=$(git tag --sort=version:refname | tail -1); export CURRENT_VERSION=$(cat CMakeLists.txt | grep VERSION | sed -n 's/.*VERSION \([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p'); if [ "$TAG" = "$CURRENT_VERSION" ]; then exit 1; fi;
  lint:
    executor: archexecutor
    steps:
      - checkout
      - run:
          command: find ./src/ -iname "*.h" -o -iname "*.cpp" | xargs clang-format --dry-run -Werror
      - run:
          command: find ./tests/ -iname "*.h" -o -iname "*.cpp" | xargs clang-format --dry-run -Werror
  build:
    executor: archexecutor
    steps:
      - checkout
      - run:
          command: cmake -S . -B Debug -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=TRUE -DCMAKE_INSTALL_PREFIX=Debug
      - run:
          command: cmake --build Debug --parallel

      - persist_to_workspace:
          root: /workspace
          paths:
            - Debug/*
  tests:
    executor: archexecutor
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run:
          command: ctest --test-dir Debug/tests --verbose

  update_tag:
    executor: archexecutor
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run:
          command: echo "$SSH_GITHUB_KEY" | tr -d '\r' | ssh-add - mkdir -p ~/.ssh chmod 700 ~/.ssh ssh-keyscan github.com >> ~/.ssh/known_hosts chmod 644 ~/.ssh/known_hosts
      - run:
          command: git config --global user.email "ymamykin@gmail.com"
      - run:
          command: git config --global user.name "YarikMamykin"
      - run:
          command: export NEW_TAG=$(cat CMakeLists.txt | grep VERSION | sed -n 's/.*VERSION \([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p'); git tag -a $NEW_TAG -m $NEW_TAG; git push origin --tags;

workflows:
  windowmanager:
    jobs:
      - check_version_increment
      - lint
      - build
      - tests:
          requires:
            - build
      - update_tag:
          filters:
            branches:
              only:
                - main
