# See: https://circleci.com/docs/configuration-reference
version: 2.1

executors:
  archexecutor:
    docker:
      - image: ym07/windowmanagerbase:latest
        auth:
          username: ym07
          password: $DOCKERHUB_TOKEN
    working_directory: /workspace

jobs:
  lint:
    executor: archexecutor
    steps:
      - checkout
      - run:
          command: find ./src/ -iname "*.h" -o -iname "*.cpp" | xargs clang-format --dry-run -Werror
      - run:
          command: find ./tests/ -iname "*.h" -o -iname "*.cpp" | xargs clang-format --dry-run -Werror
  build:
    executor: archexecutor
    steps:
      - checkout
      - run:
          command: cmake -S . -B Debug -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=TRUE -DCMAKE_INSTALL_PREFIX=Debug
      - run:
          command: cmake --build Debug --parallel

      - persist_to_workspace:
          root: /workspace
          paths:
            - Debug/*
  tests:
    executor: archexecutor
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run:
          command: ctest --test-dir Debug/tests --verbose

workflows:
  windowmanager:
    jobs:
      - lint
      - build
      - tests:
          requires:
            - build
