#include "events/AbstractKeyCode.h"

#include <X11/keysym.h>

namespace ymwm::events {
  AbstractKeyCode::Type AbstractKeyCode::a{ XK_a };
  AbstractKeyCode::Type AbstractKeyCode::b{ XK_b };
  AbstractKeyCode::Type AbstractKeyCode::c{ XK_c };
  AbstractKeyCode::Type AbstractKeyCode::d{ XK_d };
  AbstractKeyCode::Type AbstractKeyCode::e{ XK_e };
  AbstractKeyCode::Type AbstractKeyCode::f{ XK_f };
  AbstractKeyCode::Type AbstractKeyCode::g{ XK_g };
  AbstractKeyCode::Type AbstractKeyCode::h{ XK_h };
  AbstractKeyCode::Type AbstractKeyCode::i{ XK_i };
  AbstractKeyCode::Type AbstractKeyCode::j{ XK_j };
  AbstractKeyCode::Type AbstractKeyCode::k{ XK_k };
  AbstractKeyCode::Type AbstractKeyCode::l{ XK_l };
  AbstractKeyCode::Type AbstractKeyCode::m{ XK_m };
  AbstractKeyCode::Type AbstractKeyCode::n{ XK_n };
  AbstractKeyCode::Type AbstractKeyCode::o{ XK_o };
  AbstractKeyCode::Type AbstractKeyCode::p{ XK_p };
  AbstractKeyCode::Type AbstractKeyCode::q{ XK_q };
  AbstractKeyCode::Type AbstractKeyCode::r{ XK_r };
  AbstractKeyCode::Type AbstractKeyCode::s{ XK_s };
  AbstractKeyCode::Type AbstractKeyCode::t{ XK_t };
  AbstractKeyCode::Type AbstractKeyCode::u{ XK_u };
  AbstractKeyCode::Type AbstractKeyCode::v{ XK_v };
  AbstractKeyCode::Type AbstractKeyCode::w{ XK_w };
  AbstractKeyCode::Type AbstractKeyCode::x{ XK_x };
  AbstractKeyCode::Type AbstractKeyCode::y{ XK_y };
  AbstractKeyCode::Type AbstractKeyCode::z{ XK_z };
  AbstractKeyCode::Type AbstractKeyCode::A{ XK_A };
  AbstractKeyCode::Type AbstractKeyCode::B{ XK_B };
  AbstractKeyCode::Type AbstractKeyCode::C{ XK_C };
  AbstractKeyCode::Type AbstractKeyCode::D{ XK_D };
  AbstractKeyCode::Type AbstractKeyCode::E{ XK_E };
  AbstractKeyCode::Type AbstractKeyCode::F{ XK_F };
  AbstractKeyCode::Type AbstractKeyCode::G{ XK_G };
  AbstractKeyCode::Type AbstractKeyCode::H{ XK_H };
  AbstractKeyCode::Type AbstractKeyCode::I{ XK_I };
  AbstractKeyCode::Type AbstractKeyCode::J{ XK_J };
  AbstractKeyCode::Type AbstractKeyCode::K{ XK_K };
  AbstractKeyCode::Type AbstractKeyCode::L{ XK_L };
  AbstractKeyCode::Type AbstractKeyCode::M{ XK_M };
  AbstractKeyCode::Type AbstractKeyCode::N{ XK_N };
  AbstractKeyCode::Type AbstractKeyCode::O{ XK_O };
  AbstractKeyCode::Type AbstractKeyCode::P{ XK_P };
  AbstractKeyCode::Type AbstractKeyCode::Q{ XK_Q };
  AbstractKeyCode::Type AbstractKeyCode::R{ XK_R };
  AbstractKeyCode::Type AbstractKeyCode::S{ XK_S };
  AbstractKeyCode::Type AbstractKeyCode::T{ XK_T };
  AbstractKeyCode::Type AbstractKeyCode::U{ XK_U };
  AbstractKeyCode::Type AbstractKeyCode::V{ XK_V };
  AbstractKeyCode::Type AbstractKeyCode::W{ XK_W };
  AbstractKeyCode::Type AbstractKeyCode::X{ XK_X };
  AbstractKeyCode::Type AbstractKeyCode::Y{ XK_Y };
  AbstractKeyCode::Type AbstractKeyCode::Z{ XK_Z };
  AbstractKeyCode::Type AbstractKeyCode::Enter{ XK_Return };
} // namespace ymwm::events
