set(ARGPARSE_DIR ${CMAKE_BINARY_DIR}/argparse)
set(ARGPARSE_INCLUDE_DIR ${ARGPARSE_DIR}/include)
set(ARGPARSE_REPO https://github.com/p-ranav/argparse.git)

add_custom_command(OUTPUT ${ARGPARSE_DIR}
	COMMAND git clone ${ARGPARSE_REPO}
	WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
)

add_custom_command(OUTPUT ${ARGPARSE_INCLUDE_DIR}
	COMMAND cmake -S . -B ${CMAKE_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX} -DARGPARSE_BUILD_SAMPLES=OFF -DARGPARSE_BUILD_TESTS=OFF
	COMMAND cmake --build ${CMAKE_BUILD_TYPE} --parallel
	COMMAND cmake --install ${CMAKE_BUILD_TYPE}
	DEPENDS ${ARGPARSE_DIR}
	WORKING_DIRECTORY ${ARGPARSE_DIR}
)

add_custom_target(argparse_lib 
	DEPENDS ${ARGPARSE_DIR}
	DEPENDS ${ARGPARSE_INCLUDE_DIR}
)
